// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKAR0wh57vYZPTe2fk35b-W5QpEWZ1j5w',
    appId: '1:844492403574:web:c4a9da68b8da4857f28057',
    messagingSenderId: '844492403574',
    projectId: 'exam-app-edd3a',
    authDomain: 'exam-app-edd3a.firebaseapp.com',
    storageBucket: 'exam-app-edd3a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFlZF0BuKVkIltiQtzzhsLoEIMc4vBogw',
    appId: '1:844492403574:android:5ac319ac7ea0272cf28057',
    messagingSenderId: '844492403574',
    projectId: 'exam-app-edd3a',
    storageBucket: 'exam-app-edd3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOHODHMKUYI8hM5wopaP_2h_Bydz9C504',
    appId: '1:844492403574:ios:f7f864c0beb193b3f28057',
    messagingSenderId: '844492403574',
    projectId: 'exam-app-edd3a',
    storageBucket: 'exam-app-edd3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOHODHMKUYI8hM5wopaP_2h_Bydz9C504',
    appId: '1:844492403574:ios:f7f864c0beb193b3f28057',
    messagingSenderId: '844492403574',
    projectId: 'exam-app-edd3a',
    storageBucket: 'exam-app-edd3a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKAR0wh57vYZPTe2fk35b-W5QpEWZ1j5w',
    appId: '1:844492403574:web:841c037ac80ab1d1f28057',
    messagingSenderId: '844492403574',
    projectId: 'exam-app-edd3a',
    authDomain: 'exam-app-edd3a.firebaseapp.com',
    storageBucket: 'exam-app-edd3a.firebasestorage.app',
  );
}
